-- Drop tables

DROP TABLE IF EXISTS friendships;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS film_mpas;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS mpas;
DROP TABLE IF EXISTS users;